### ISSUE TITLE
Change ```eval_envs``` to ```num_eval_envs```

### ISSUE THREAD

**Issue by alirahkay** [danijar/dreamerv2#21]
https://github.com/danijar/dreamerv2/blob/e02ceb9a77596e695a66d099e749b6bdf62db50e/dreamerv2/train.py#L129

Since the number of evaluation environments is ```num_eval_envs```, I think there should be a change at the end of this line.

**Comment by danijar** [comment]
Thanks! Parallel training is not really tested within this code base.
