### ISSUE TITLE
How to save and reload trained dreamerv2 models

### ISSUE THREAD

**Issue by Adaickalavan** [danijar/dreamerv2#26]
1) How can I save a trained dreamerv2 model? 
2) How can I reuse or load a previously trained dreamerv2 model for (i) evaluation or (ii) as a base for further training, at a later time?

**Comment by danijar** [comment]
The weights are checkpointed into pickle files and if you run training with the same logdir, it will automatically restore the checkpoint. Hope that helps.

**Comment by azizbelkhiria** [comment]
Is it possible to restore previous checkpoints or does the model overwrite the checkpoint at each time?
