### ISSUE TITLE
How many environment steps per update?

### ISSUE THREAD

**Issue by mctigger** [danijar/dreamerv2#29]
Hi danijar,
how many environment steps are you running per update?
In the paper it is 4 (so after every step the agent makes it is updated because of action repeat?), but here in the config it says ` train_every: 16`. What is the correct number?

Best,
Tim

**Comment by danijar** [comment]
Hi Tim, those are both correct. It's 16 env steps or 4 agent steps. The action repeat introduces the factor of 4 between the two.

**Comment by mctigger** [comment]
Thank you for answering so quickly!

In the paper in the hyperparamters section it says _Environment steps per update: 4_. So in the paper it should actually be _Agent Steps per update: 4_ or _Environment steps per update: 16_ if I understand you correctly?

**Comment by danijar** [comment]
Ah, yes. It's every 16 frames or 4 actions. I'll update the paper to make it clearer.
