### ISSUE TITLE
KeyError: 'dmc' while trying to run walker?

### ISSUE THREAD

**Issue by mrmarten** [danijar/dreamerv2#31]
This is the commandline and output i get:

`(tf2) marten@dpserver:~/rl/dreamerv2$ python3 dreamerv2/train.py --logdir ~/logdir/dmc_walker_walk/dreamerv2/1 --configs dmc --task dmc_walker_walk
Traceback (most recent call last):
  File "dreamerv2/train.py", line 196, in <module>
    main()
  File "dreamerv2/train.py", line 37, in main
    config = config.update(configs[name])
KeyError: 'dmc'`

**Comment by vmichals** [comment]
The proper config names are `dmc_vision` or `dmc_proprio` (see `dreamerv2/configs.yaml`) depending on whether you want to train on visual or proprioceptive inputs.

**Comment by danijar** [comment]
Thanks, fixed!
