### ISSUE TITLE
What does "openl" do / mean? 

### ISSUE THREAD

**Issue by hueds** [danijar/dreamerv2#33]
Just curious about the variable naming in this snippet of code.
![Screen Shot 2022-04-11 at 1 06 17 PM](https://user-images.githubusercontent.com/13341926/162793020-8d661439-1394-45f5-a3c2-05e193d439cf.png)

**Comment by danijar** [comment]
Thanks for the question. It's short for open-loop prediction, meaning that the model predicts into the future given actions for multiple steps without seeing any intermediate images.
