### ISSUE TITLE
Should policy state be reset after every episode? 

### ISSUE THREAD

**Issue by edwhu** [danijar/dreamerv2#36]
It seems like the state of the agent (`self._state`) is not initialized to 0 on reset. Only in the very first episode, it is `None`, so it will be set to 0s. Since `driver.reset()` is never called again in `api.py`, `self._state` will be carried over from previous episodes on episode reset.
Is this intentional?

https://github.com/danijar/dreamerv2/blob/07d906e9c4322c6fc2cd6ed23e247ccd6b7c8c41/dreamerv2/common/driver.py#L32-L40

**Comment by danijar** [comment]
Yep, the world model resets its state based on the `is_first` flag: https://github.com/danijar/dreamerv2/blob/07d906e9c4322c6fc2cd6ed23e247ccd6b7c8c41/dreamerv2/common/nets.py#L94
