### ISSUE TITLE
Understanding re-clipping in Truncated Normal distribution

### ISSUE THREAD

**Issue by pvskand** [danijar/dreamerv2#50]
Hi,

I was looking at the `TruncNormalDist` [code](https://github.com/danijar/dreamerv2/blob/main/dreamerv2/common/dists.py#L81-L84) and was wondering why were the samples re-clipped ('re' because they are already in `[-1, 1]` because of `tfd.TruncatedNormal`'s sampling).
In practice it seems to me that this wouldn't create an issue as it is only re-clipped by `1e-6`, but I am curious if I'm missing something.

Thanks!

**Comment by danijar** [comment]
That's just because the log prob is not differentiable in the bounds, but I think never versions of TFP may give them a gradient already.
