### ISSUE TITLE
Code  For: "Algorithm 1: Straight-Through Gradients with Automatic Differentiation"

### ISSUE THREAD

**Issue by lucasmgomez** [danijar/dreamerv2#59]
I am having trouble finding where the code for the Algorithm 1 described in the paper. Could you please point me to it?

**Comment by danijar** [comment]
https://github.com/danijar/dreamerv3/blob/a1cf96c05fc9e1e1716ff918d1da75bd05d456bf/dreamerv3/jaxutils.py#L115
